-- WHERE 절 서브쿼리 위한 테이블 생성

CREATE TABLE EX_CARD(
REGION_CODE VARCHAR2(100),
PRODUCT_CODE VARCHAR2(100),
REASON VARCHAR2(100))

SELECT * FROM EX_CARD

INSERT INTO EX_CARD VALUES('A60','PRODUCT4','CARD NOT RELEASED');
INSERT INTO EX_CARD VALUES('A60','PRODUCT59','CARD MINWON');
INSERT INTO EX_CARD VALUES('A60','PRODUCT4','CARD MINWON');

-- WHERE 절의 서브쿼리
SELECT *
FROM KOPO_CHANNEL_SEASONALITY_NEW
WHERE 1=1
AND REGIONID||'_'||PRODUCT NOT IN 
    (SELECT DISTINCT REGION_CODE||'_'||PRODUCT_CODE
     FROM EX_CARD )
     

-- FROM절 서브쿼리
SELECT COUNT(*)
FROM
(
    SELECT REGIONID, 
            PRODUCT,
            YEARWEEK,
            SUM(QTY) AS SUM_QTY
    FROM KOPO_CHANNEL_SEASONALITY_NEW
    GROUP BY REGIONID, PRODUCT,YEARWEEK        
    ORDER BY REGIONID, PRODUCT,YEARWEEK
)
       
SELECT A.*,
        (SELECT AVG(QTY)
        FROM KOPO_CHANNEL_SEASONALITY_NEW
        WHERE REGIONID = A.REGIONID
        AND PRODUCT = A.PRODUCT
        GROUP BY A.REGIONID, A.PRODUCT) AS SUM_QTY
FROM KOPO_CHANNEL_SEASONALITY_NEW A

SELECT A.* 
FROM 
(
    -- 실적중에 14년도 15주차 이후 데이터
    SELECT * 
    FROM KOPO_CHANNEL_SEASONALITY_NEW 
    WHERE 1=1
    AND YEARWEEK > 201415) A
)
